### ISSUE TITLE
(scrape) Why PostgreSQL and not simply SQLite?

### ISSUE THREAD

**Issue by martinbetz** [econchick/new-coder#101]
I like your tutorials, but I wonder why you chose PostgreSQL for the scraping tutorial.

From what I see a simple SQLite database would be sufficient for a local scraping script. PostgreSQL is a lot more complicated to set up and maintain.

But probably you have good reason for your choice. Let me know!

**Comment by econchick** [comment]
You're right that sqlite is very sufficient - there's no reason not to use sqlite.  

I elected postgres simply because of it's popularity, and I wanted to get new coders exposed to a widely-used "buzzword" database.
