### ISSUE TITLE
Run `python —version` (and pip —version etc.) to make sure python is installed

### ISSUE THREAD

**Issue by mathonsunday** [econchick/new-coder#115]
Currently we run 'python' and 'pip' rather than 'python --version' and 'pip --version' on the [Setting Up Your Computer](http://newcoder.io/begin/setup-your-machine/) page. Checking the version of your installed software and actually running it are two different things. The command line output for the current instructions might confuse new people.

**Comment by econchick** [comment]
Switched for `pip` but left `python` there since I want people to start getting use to the Python shell.

Will push an update later today.
