### ISSUE TITLE
APIs tutorial part 2 refers to nonexistent parse function

### ISSUE THREAD

**Issue by helenst** [econchick/new-coder#145]
see http://newcoder.io/api/part-2/#for-the-curious
There's no `parse` function and the `for deal in selector` line does not exist.

Maybe that paragraph should be moved down beneath the next block of code and updated to refer to `get_platforms` instead?

**Comment by econchick** [comment]
Thanks @helenst ! I've fixed this in my current local version and will update the website later today.
