### ISSUE TITLE
tutorial request

### ISSUE THREAD

**Issue by edirg559** [econchick/new-coder#153]
Hi I am wondering if you would be interested in making a tutorial using Django framework to make a web application. Your tutorial series will be complete by having one tutorial of making an end product (webapp) in Python programming.

**Comment by econchick** [comment]
The Django documentation has a full tutorial already. I'm assuming you already went through it and are probably looking for another one beyond a poll application, but it is actually quite complete in terms of touching major aspects of using Django.

**Comment by willingc** [comment]
The Django website lists a number of resources: https://code.djangoproject.com/wiki/DjangoResources for folks. I've included the link here for visitors that may find this information useful in the future.

@edirg559 Thanks for filing the request, and I hope you enjoy the newcoder.io tutorials. As @econchick mentions, the official Django tutorial is very good at covering how to create a web application.

I'm closing this issue yet marking it "blue sky" (something that is not in the current project scope). This allows the project team to refer to it easily in future years for planning purposes.
