### ISSUE TITLE
Writing a search engine

### ISSUE THREAD

**Issue by hobz-** [econchick/new-coder#169]
Would like to better understand python and the inter-tron through building my own search engine. Is this possible with python?

**Comment by econchick** [comment]
Hi @hobz- One of Udacity's first course they made was an intro to CS with how to build your own search engine in Python - I suggest you check it out [here](https://www.udacity.com/course/cs101).

Best of luck!

**Comment by hobz-** [comment]
Thanks Lynn, I overlooked Udacity and didn't notice they built a search
engine because it seemed very basic, but going to work through it now.

Cheers
