### ISSUE TITLE
dataviz: "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-DGNW52/matplotlib"

### ISSUE THREAD

**Issue by lukehinds** [econchick/new-coder#181]
At the end of running 'pip install -r requirements.txt' in the dataviz project

I get the following error: 

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-DGNW52/matplotlib

**Comment by lukehinds** [comment]
I noted the part in the tutorial about hitting issues here, so I compiled instead. sorry about the noise of an unneeded issue.

**Comment by merwok** [comment]
Better to open an unneeded ticket than not asking for help.  I’m glad you found a solution!

**Comment by lukehinds** [comment]
Many thanks. I did hit a lot of issues trying to get freetype to compile, I will take another look tonight.
