### ISSUE TITLE
Encourage py3.x instead of py2.x installation

### ISSUE THREAD

**Issue by alvations** [econchick/new-coder#191]
On [one of the first few pages of newcoder.io](http://newcoder.io/begin/how-to-work-through-tutorials/) , it suggests py2.7 installation. It would be great if new coders starts with py3.x instead. It's a radical move but it's a step towards [PEP 0404](https://www.python.org/dev/peps/pep-0404/) and  http://blog.startifact.com/guido_no.jpg =)

**Comment by econchick** [comment]
@alvations this would require a complete update for all the tutorials as they were originally written for 2.x.

I'm going to go ahead and close this since there are a few issues to already track 3.x development.
