### ISSUE TITLE
Update tutorials to include python 3

### ISSUE THREAD

**Issue by econchick** [econchick/new-coder#28]

**Comment by tensory** [comment]
Hi. I'm interested in contributing at least as far as setting up virtualenv for Python 3 on Macs.

**Comment by econchick** [comment]
Hey @tensory - you're awesome. Thanks for that PR! This is giving me the idea to make use of the wiki on github to help folks wanting to contribute with actually concrete TODOs.

**Comment by JoshLimGuorong** [comment]
Python 3 with windows 10 please

**Comment by nituadhikari** [comment]
Will these projects still work with Python 3?
