### ISSUE TITLE
Unable to find virtualenvwrapper.sh

### ISSUE THREAD

**Issue by econchick** [econchick/new-coder#39]
Add directions to find the script file after pip installs it.

Mostly issues with Ubuntu, and Mac w/ more than one Python version.

**Comment by merwok** [comment]
@econchick You closed this ticket as duplicate (of #83 I assume), but the other ticket was already closed as duplicate of this one.

**Comment by econchick** [comment]
I closed it because I added a fix for it.

**Comment by merwok** [comment]
Ah! :‑)
