### ISSUE TITLE
Setup in windows

### ISSUE THREAD

**Issue by Vlissides** [econchick/new-coder#66]
Virtualenvwrapper isn't prepared for windows you can use instead virtualenvwrapper-win. Also during the installation of the libraries which are based on c modules, a windows user can have problems if they doesn't have visual studio or at least its libraries. They can use instead precompiled modules from here http://www.lfd.uci.edu/~gohlke/pythonlibs/ however they won't have a virtual environment.

**Comment by econchick** [comment]
Updated - hopefully the setup works now (I have no Windows machine easily accessible right now to test).  Will push update to site later today.
